package com.engine.sound;

public interface ISoundPort {
	public enum MusicID {
		DUNGEON,
		UNDERGROUND,
		MINI_BOSS,
		DUNGEON_NIGHTMARE,
		NIGHTMARE_DEFEATED,
		GET_INSTRUMENT,
		FULL_MOON_CELLO,
		POWER_UP,
		GAME_OVER,
	}
	public enum SoundID {
		SECRET_SOLVED,
		SECRET_ERROR,
		KEY_PRESENT,
		KEY_BOUNCE,
		BOMB_EXPLODE,
		SWORD_WALL_COLLISION,

		ENEMY_HIT,
		ENEMY_HIT_POWER_UP,
		ENEMY_DIE,
		ENEMY_DIE_POWER_UP,
		ENEMY_FALL,
		ENEMY_JUMP,
		BLADE_TRAP_CHARGE,

		BOSS_HIT,
		BOSS_DIE,
		BOSS_JUMP,
		BOSS_DEATH_FLAME,
		BOSS_DEATH_FLAME_FAST,
		ROLL,
		MOLDORM_WALK,
		MOLDORM_SEGMENT_EXPLODE1,
		MOLDORM_SEGMENT_EXPLODE2,

		SWORD_SLASH_1,
		SWORD_SLASH_2,
		SWORD_SLASH_3,
		SWORD_SLASH_4,
		SWORD_POWER_UP,
		SWORD_SPIN,
		SHIELD_UP,
		LINK_JUMP,
		LINK_BOUNCE,
		LINK_LAND,
		LINK_FALL,
		LINK_HURT,
		LINK_PICK_UP,
		LINK_THROW,
		LINK_DIE,
		DEFLECT,

		ROCK_PUSH,

		MAGIC_POWDER_SPRINKLE,
		FIRE_IGNITE,

		CHEST_OPEN,
		CHEST_LESSER_ITEM_FOUND,
		CHEST_MAJOR_ITEM_FOUND,
		ITEM_TAKE1,
		ITEM_TAKE2,
		HEART_CONTAINER_TAKE,
		POWER_UP_TAKE,
		RUPEE_QUANTITY_CHANGE,
		SWITCH_PRESSED,
		DOOR_CLOSE,

		ONE_WAY_DOOR,
		STAIRS,
		FLOOR_CRUMBLE,
		ROCK_DESTROYED,

		EQUIPMENT_MENU_OPEN,
		EQUIPMENT_MENU_CLOSE,
		MENU_CURSOR,
		MENU_SELECT,
		TEXT_LETTER,
		TEXT_END,

		TELEPORT_APPEARS,
		TELEPORT_ENTER,
		TELEPORT_DUNGEON_OUT,
	}

	void setMusicVolume(int volume);
	void changeMusic(MusicID id);
	void stopMusic();
	boolean isMusicPlaying(MusicID id);
	void playSound(SoundID id);
	void playSoundNonSimultaneous(SoundID id);
	void stopAllSound();
}
